# Generated by Django 5.2.15 on 2026-09-16 09:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0037_grade_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationType',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('weightage', models.DecimalField(decimal_places=2, default=0, help_text='Weightage percentage', max_digits=5)),
                ('max_marks', models.DecimalField(decimal_places=2, default=100, help_text='Maximum marks', max_digits=6)),
                ('frequency', models.PositiveIntegerField(default=1, help_text='Number of times this examination type occurs in an academic year')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examination_types', to='school.branch')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_types', to='school.school')),
            ],
            options={
                'db_table': 'examination_types',
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='school.academicyear')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examinations', to='school.branch')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='school.school')),
                ('examination_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examinations', to='examination.examinationtype')),
            ],
            options={
                'db_table': 'examinations',
            },
        ),
        migrations.CreateModel(
            name='ExaminationGrade',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_grades', to='examination.examination')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_grades', to='school.grade')),
            ],
            options={
                'db_table': 'examination_grades',
                'indexes': [models.Index(fields=['examination'], name='examination_examina_961e3c_idx'), models.Index(fields=['grade'], name='examination_grade_i_357d72_idx')],
                'constraints': [models.UniqueConstraint(fields=('examination', 'grade'), name='unique_examination_grade')],
            },
        ),
        migrations.AddIndex(
            model_name='examinationtype',
            index=models.Index(fields=['school'], name='examination_school__c59d8d_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationtype',
            index=models.Index(fields=['branch'], name='examination_branch__78f2ca_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationtype',
            index=models.Index(fields=['status'], name='examination_status_dba2d9_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationtype',
            index=models.Index(fields=['school', 'status'], name='examination_school__6b5010_idx'),
        ),
        migrations.AddConstraint(
            model_name='examinationtype',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_examination_type_name_per_school'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['school'], name='examination_school__96755c_idx'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['branch'], name='examination_branch__a0f3eb_idx'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['academic_year'], name='examination_academi_f2a95f_idx'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['examination_type'], name='examination_examina_bcf0a2_idx'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['status'], name='examination_status_6dd3b9_idx'),
        ),
        migrations.AddIndex(
            model_name='examination',
            index=models.Index(fields=['school', 'academic_year'], name='examination_school__813d2e_idx'),
        ),
    ]
