# Generated by Django 5.2.15 on 2026-09-16 14:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0001_initial'),
        ('school', '0037_grade_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExaminationSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('maximum_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('passing_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='examination.examination')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_schedules', to='school.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_schedules', to='school.subject')),
            ],
            options={
                'db_table': 'examination_schedules',
            },
        ),
        migrations.CreateModel(
            name='ExaminationResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marks_obtained', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examination.examination')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_results', to='school.student')),
                ('examination_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examination.examinationschedule')),
            ],
            options={
                'db_table': 'examination_results',
            },
        ),
        migrations.CreateModel(
            name='ExaminationAttendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=20)),
                ('attendance_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='examination.examination')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination_attendance', to='school.student')),
                ('examination_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='examination.examinationschedule')),
            ],
            options={
                'db_table': 'examination_attendance',
            },
        ),
        migrations.CreateModel(
            name='GradeConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=10)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_configurations', to='school.academicyear')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grade_configurations', to='school.branch')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_configurations', to='school.school')),
            ],
            options={
                'db_table': 'grade_configurations',
            },
        ),
        migrations.CreateModel(
            name='HallTicket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hall_ticket_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled')], default='GENERATED', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_tickets', to='examination.examination')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hall_tickets', to='school.student')),
            ],
            options={
                'db_table': 'hall_tickets',
            },
        ),
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('obtained_marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('grade', models.CharField(blank=True, max_length=10, null=True)),
                ('grade_point', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('result', models.CharField(blank=True, max_length=20, null=True)),
                ('teacher_remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='examination.examination')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='school.student')),
            ],
            options={
                'db_table': 'report_cards',
            },
        ),
        migrations.AddIndex(
            model_name='examinationschedule',
            index=models.Index(fields=['examination'], name='examination_examina_1353f2_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationschedule',
            index=models.Index(fields=['grade'], name='examination_grade_i_6dc4ce_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationschedule',
            index=models.Index(fields=['subject'], name='examination_subject_6efea5_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationschedule',
            index=models.Index(fields=['exam_date'], name='examination_exam_da_61c795_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationschedule',
            index=models.Index(fields=['examination', 'grade'], name='examination_examina_3a1bf9_idx'),
        ),
        migrations.AddConstraint(
            model_name='examinationschedule',
            constraint=models.UniqueConstraint(fields=('examination', 'grade', 'subject'), name='unique_exam_schedule_subject'),
        ),
        migrations.AddIndex(
            model_name='examinationresult',
            index=models.Index(fields=['examination'], name='examination_examina_14feac_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationresult',
            index=models.Index(fields=['examination_schedule'], name='examination_examina_02c4dd_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationresult',
            index=models.Index(fields=['student'], name='examination_student_68b8e4_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationresult',
            index=models.Index(fields=['status'], name='examination_status_a5bb39_idx'),
        ),
        migrations.AddConstraint(
            model_name='examinationresult',
            constraint=models.UniqueConstraint(fields=('examination_schedule', 'student'), name='unique_exam_result_per_student'),
        ),
        migrations.AddIndex(
            model_name='examinationattendance',
            index=models.Index(fields=['examination'], name='examination_examina_7cf3b3_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationattendance',
            index=models.Index(fields=['examination_schedule'], name='examination_examina_e2c588_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationattendance',
            index=models.Index(fields=['student'], name='examination_student_b005f7_idx'),
        ),
        migrations.AddIndex(
            model_name='examinationattendance',
            index=models.Index(fields=['status'], name='examination_status_3787b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='examinationattendance',
            constraint=models.UniqueConstraint(fields=('examination_schedule', 'student'), name='unique_exam_attendance_per_student'),
        ),
        migrations.AddIndex(
            model_name='gradeconfiguration',
            index=models.Index(fields=['school'], name='grade_confi_school__20cf4f_idx'),
        ),
        migrations.AddIndex(
            model_name='gradeconfiguration',
            index=models.Index(fields=['branch'], name='grade_confi_branch__c63f6b_idx'),
        ),
        migrations.AddIndex(
            model_name='gradeconfiguration',
            index=models.Index(fields=['academic_year'], name='grade_confi_academi_a0ce63_idx'),
        ),
        migrations.AddConstraint(
            model_name='gradeconfiguration',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'grade'), name='unique_grade_configuration'),
        ),
        migrations.AddIndex(
            model_name='hallticket',
            index=models.Index(fields=['examination'], name='hall_ticket_examina_d2b632_idx'),
        ),
        migrations.AddIndex(
            model_name='hallticket',
            index=models.Index(fields=['student'], name='hall_ticket_student_9a221e_idx'),
        ),
        migrations.AddIndex(
            model_name='hallticket',
            index=models.Index(fields=['status'], name='hall_ticket_status_e4f1c5_idx'),
        ),
        migrations.AddConstraint(
            model_name='hallticket',
            constraint=models.UniqueConstraint(fields=('examination', 'student'), name='unique_hall_ticket_per_exam_student'),
        ),
        migrations.AddConstraint(
            model_name='hallticket',
            constraint=models.UniqueConstraint(fields=('examination', 'hall_ticket_number'), name='unique_hall_ticket_number_per_exam'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['examination'], name='report_card_examina_6cbad5_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['student'], name='report_card_student_68d3ea_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['status'], name='report_card_status_fba963_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportcard',
            constraint=models.UniqueConstraint(fields=('examination', 'student'), name='unique_report_card_per_exam_student'),
        ),
    ]
