# Generated by Django 5.2.15 on 2026-09-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0003_examination_result_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='reporting_date',
            field=models.DateField(default='2026-08-24'),
            preserve_default=False,
        ),
    ]
