# Generated by Django 5.2.15 on 2026-09-23 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0004_examination_reporting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examination',
            name='reporting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
