# Generated by Django 5.2.15 on 2026-09-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0005_alter_examination_reporting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationresult',
            name='external_marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='examinationresult',
            name='internal_marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='examinationresult',
            name='practical_marks',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='examinationresult',
            name='marks_obtained',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
