# Generated by Django 5.2.15 on 2026-09-24 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0006_examinationresult_external_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationresult',
            name='grade_point',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
