# Generated by Django 5.2.15 on 2026-09-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0007_examinationresult_grade_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeconfiguration',
            name='grade_point',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
