# Generated by Django 5.2.15 on 2026-09-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0008_gradeconfiguration_grade_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='examinationresult',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
