# Generated by Django 5.2.15 on 2026-09-24 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examination', '0009_examinationresult_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeconfiguration',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
    ]
