# Generated by Django 5.2.14 on 2026-05-09 04:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='active', max_length=50)),
                ('signup_invite_code', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'UserMaster',
                'verbose_name_plural': 'UserMasters',
                'db_table': 'user_master',
            },
        ),
        migrations.CreateModel(
            name='CronJobLocks',
            fields=[
                ('job_name', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('acquired', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cronjob_locks',
            },
        ),
        migrations.CreateModel(
            name='ShoppingList',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('access_type', models.CharField(choices=[('ONLY_ME', 'Only Me'), ('FAMILY', 'Family'), ('SPECIFIC', 'Specific')], default='FAMILY', max_length=20)),
                ('access_ids', models.JSONField(blank=True, default=list)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CloseGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='close_group', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'close_group',
            },
        ),
        migrations.CreateModel(
            name='CloseGroupMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=200, null=True)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('JOINED', 'Joined'), ('REMOVED', 'Removed')], default='INVITED', max_length=20)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='close_group_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('close_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.closegroup')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='close_group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'close_group_member',
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('icon', models.CharField(max_length=500, null=True)),
                ('description', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_families', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'family',
            },
        ),
        migrations.CreateModel(
            name='FamilyFeed',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('FAMILY', 'Entire Family'), ('SELECTED', 'Selected Members'), ('ONLY_ME', 'Only Me')], default='FAMILY', max_length=20)),
                ('reaction_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('share_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_feeds', to=settings.AUTH_USER_MODEL)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeds', to='core.family')),
            ],
            options={
                'db_table': 'family_feed',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyFeedComment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.familyfeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'family_feed_comment',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FamilyFeedMedia',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video')], max_length=10)),
                ('media_url', models.CharField(max_length=500)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='core.familyfeed')),
            ],
            options={
                'db_table': 'family_feed_media',
            },
        ),
        migrations.CreateModel(
            name='FamilyFeedReaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reaction', models.CharField(choices=[('LOVE', 'Love'), ('LIKE', 'Like'), ('WOW', 'Wow'), ('SAD', 'Sad'), ('ANGRY', 'Angry'), ('HAHA', 'HaHa')], max_length=20)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='core.familyfeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'family_feed_reaction',
            },
        ),
        migrations.CreateModel(
            name='FamilyFeedSave',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='core.familyfeed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'family_feed_save',
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100)),
                ('f_name', models.CharField(max_length=100, null=True)),
                ('l_name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('relation', models.CharField(max_length=100, null=True)),
                ('role', models.CharField(choices=[('OWNER', 'Owner'), ('ADMIN', 'Admin'), ('MEMBER', 'Member')], default='MEMBER', max_length=20)),
                ('status', models.CharField(choices=[('INVITED', 'Invited'), ('JOINED', 'Joined'), ('REMOVED', 'Removed')], default='INVITED', max_length=20)),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.family')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'family_member',
            },
        ),
        migrations.CreateModel(
            name='FamilyFeedVisibility',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visible_members', to='core.familyfeed')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.familymember')),
            ],
            options={
                'db_table': 'family_feed_visibility',
            },
        ),
        migrations.CreateModel(
            name='InvitationCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('code_type', models.CharField(choices=[('generic', 'Generic'), ('targeted', 'Targeted')], default='generic', max_length=20)),
                ('target_email', models.EmailField(max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'InvitationCode',
                'verbose_name_plural': 'InvitationCodes',
                'db_table': 'invitation_code',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='invitation__code_f2a167_idx'), models.Index(fields=['is_active'], name='invitation__is_acti_0af483_idx')],
            },
        ),
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(blank=True, max_length=20, null=True)),
                ('reason', models.TextField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'MembershipApplication',
                'verbose_name_plural': 'MembershipApplications',
                'db_table': 'membership_application',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='membership__email_e58ff5_idx'), models.Index(fields=['status'], name='membership__status_1cf474_idx')],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.TextField()),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('view_access', models.CharField(choices=[('ME', 'Me'), ('FAMILY', 'Family'), ('SPECIFIC', 'Specific')], default='ME', max_length=10)),
                ('edit_access', models.CharField(choices=[('ME', 'Me'), ('FAMILY', 'Family'), ('SPECIFIC', 'Specific')], default='ME', max_length=10)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notes',
            },
        ),
        migrations.CreateModel(
            name='NoteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('access_type', models.CharField(choices=[('VIEW', 'View'), ('EDIT', 'Edit')], max_length=10)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_list', to='core.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notes_access',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('otp', models.CharField(max_length=8)),
                ('purpose', models.CharField(choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('login_fallback', 'Login Fallback')], default='email_verification', max_length=30)),
                ('expires_at', models.DateTimeField()),
                ('retry_count', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('device_id', models.CharField(max_length=255, null=True)),
                ('country_code', models.CharField(max_length=10, null=True)),
                ('device_registered', models.BooleanField(default=False)),
                ('is_used', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'OTP',
                'verbose_name_plural': 'OTPs',
                'db_table': 'otp',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mobile', 'expires_at', 'otp'], name='otp_mobile_481681_idx'), models.Index(fields=['email', 'expires_at', 'otp'], name='otp_email_d2629d_idx'), models.Index(fields=['purpose', 'email', 'expires_at'], name='otp_purpose_159f81_idx')],
            },
        ),
        migrations.CreateModel(
            name='ListItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_name', models.CharField(blank=True, max_length=50, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('IN_QUEUE', 'In Queue'), ('SECURED', 'Secured')], default='IN_QUEUE', max_length=20)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.shoppinglist')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SignupSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('invite_code', models.CharField(max_length=50)),
                ('otp_verified', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'signup_session',
                'indexes': [models.Index(fields=['email'], name='signup_sess_email_1eb541_idx'), models.Index(fields=['invite_code'], name='signup_sess_invite__6deef3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='closegroup',
            index=models.Index(fields=['owner'], name='close_group_owner_i_3f6fce_idx'),
        ),
        migrations.AddIndex(
            model_name='closegroupmember',
            index=models.Index(fields=['close_group'], name='close_group_close_g_749bad_idx'),
        ),
        migrations.AddIndex(
            model_name='closegroupmember',
            index=models.Index(fields=['user'], name='close_group_user_id_234b1d_idx'),
        ),
        migrations.AddIndex(
            model_name='closegroupmember',
            index=models.Index(fields=['email'], name='close_group_email_dfa515_idx'),
        ),
        migrations.AddIndex(
            model_name='closegroupmember',
            index=models.Index(fields=['status'], name='close_group_status_6a7622_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='closegroupmember',
            unique_together={('close_group', 'email')},
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['owner'], name='family_owner_i_4424a4_idx'),
        ),
        migrations.AddIndex(
            model_name='family',
            index=models.Index(fields=['is_active'], name='family_is_acti_e80b2d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='familyfeedreaction',
            unique_together={('feed', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='familyfeedsave',
            unique_together={('feed', 'user')},
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['family'], name='family_memb_family__05017e_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['user'], name='family_memb_user_id_dfc548_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['email'], name='family_memb_email_270f79_idx'),
        ),
        migrations.AddIndex(
            model_name='familymember',
            index=models.Index(fields=['status'], name='family_memb_status_3fa90d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='familymember',
            unique_together={('family', 'email')},
        ),
        migrations.AlterUniqueTogether(
            name='familyfeedvisibility',
            unique_together={('feed', 'member')},
        ),
    ]
