# Generated by Django 5.2.14 on 2026-05-26 16:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaster',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('mobile', models.CharField(max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending', 'Pending')], default='active', max_length=50)),
                ('signup_invite_code', models.CharField(max_length=50, null=True)),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('gender', models.CharField(max_length=255, null=True)),
                ('profile_image', models.CharField(max_length=500, null=True)),
                ('is_profile_updated', models.BooleanField(default=False)),
                ('is_password_updated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'UserMaster',
                'verbose_name_plural': 'UserMasters',
                'db_table': 'user_master',
            },
        ),
        migrations.CreateModel(
            name='CronJobLocks',
            fields=[
                ('job_name', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False)),
                ('acquired', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cronjob_locks',
            },
        ),
    ]
