# Generated by Django 6.0.5 on 2026-05-09 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='noteaccess',
            name='note',
        ),
        migrations.RemoveField(
            model_name='noteaccess',
            name='user',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='icon',
            new_name='family_picture',
        ),
        migrations.RemoveField(
            model_name='closegroupmember',
            name='name',
        ),
        migrations.RemoveField(
            model_name='family',
            name='description',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='f_name',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='familymember',
            name='l_name',
        ),
        migrations.AddField(
            model_name='usermaster',
            name='profile_image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MEMBER', 'Member')], default='MEMBER', max_length=20),
        ),
        migrations.DeleteModel(
            name='ListItem',
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='NoteAccess',
        ),
    ]
