# Generated by Django 6.0.5 on 2026-05-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_note_creator_remove_noteaccess_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationcode',
            name='created_by_user_id',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='invitationcode',
            name='current_uses',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='invitationcode',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='invitationcode',
            name='max_uses',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
