# Generated by Django 5.2.14 on 2026-06-01 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='signup_invite_code',
        ),
    ]
