# Generated by Django 6.0.5 on 2026-05-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_invitationcode_created_by_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='usermaster',
            name='is_profile_updated',
            field=models.BooleanField(default=False),
        ),
    ]
