# Generated by Django 6.0.5 on 2026-05-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usermaster_profile_updated_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='familymember',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='gender',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='familymember',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
