# Generated by Django 5.2.14 on 2026-06-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_usermaster_signup_invite_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermaster',
            options={},
        ),
        migrations.AddField(
            model_name='usermaster',
            name='username',
            field=models.CharField(default='9876543210', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='email',
            field=models.EmailField(max_length=255, null=True),
        ),
        migrations.AlterModelTable(
            name='usermaster',
            table=None,
        ),
    ]
