# Generated by Django 6.0.5 on 2026-05-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_familymember_first_name_familymember_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('SPOUSE', 'Spouse'), ('PARENT', 'Parent'), ('CHILD', 'Child'), ('BROTHER', 'Brother'), ('SISTER', 'Sister'), ('GRANDPARENT', 'Grandparent'), ('GRANDCHILD', 'Grandchild'), ('AUNT', 'Aunt'), ('UNCLE', 'Uncle'), ('COUSIN', 'Cousin'), ('IN_LAW', 'In-Law'), ('FRIEND', 'Friend'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
