# Generated by Django 5.2.14 on 2026-06-03 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_usermaster_options_usermaster_username_and_more'),
        ('school', '0006_alter_school_email_alter_schoollead_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpermissions',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_direct_permissions', to='school.school'),
        ),
        migrations.AlterField(
            model_name='userroles',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='school.school'),
        ),
    ]
