# Generated by Django 6.0.5 on 2026-05-12 16:13

from django.db import migrations, models


def lowercase_family_member_enums(apps, schema_editor):
    FamilyMember = apps.get_model('core', 'FamilyMember')

    enum_mappings = {
        'role': {
            'OWNER': 'owner',
            'MEMBER': 'member',
        },
        'status': {
            'INVITED': 'invited',
            'JOINED': 'joined',
            'REMOVED': 'removed',
        },
        'relation': {
            'SPOUSE': 'spouse',
            'PARENT': 'parent',
            'CHILD': 'child',
            'BROTHER': 'brother',
            'SISTER': 'sister',
            'GRANDPARENT': 'grandparent',
            'GRANDCHILD': 'grandchild',
            'AUNT': 'aunt',
            'UNCLE': 'uncle',
            'COUSIN': 'cousin',
            'IN_LAW': 'in_law',
            'FRIEND': 'friend',
            'OTHER': 'other',
        },
    }

    for field_name, mapping in enum_mappings.items():
        for old_value, new_value in mapping.items():
            FamilyMember.objects.filter(**{field_name: old_value}).update(**{field_name: new_value})


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_familymember_relation'),
    ]

    operations = [
        migrations.RunPython(lowercase_family_member_enums, noop_reverse),
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('brother', 'Brother'), ('sister', 'Sister'), ('grandparent', 'Grandparent'), ('grandchild', 'Grandchild'), ('aunt', 'Aunt'), ('uncle', 'Uncle'), ('cousin', 'Cousin'), ('in_law', 'In-Law'), ('friend', 'Friend'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('joined', 'Joined'), ('removed', 'Removed')], default='invited', max_length=20),
        ),
    ]
