# Generated by Django 5.2.14 on 2026-06-04 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_userpermissions_school_alter_userroles_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='is_password_updated',
        ),
    ]
