# Generated by Django 5.2.14 on 2026-06-12 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_modules_deleted_at_modules_deleted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
