# Generated by Django 5.2.14 on 2026-06-12 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_usermaster_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermaster',
            name='occupation',
        ),
    ]
