# Generated by Django 5.2.14 on 2026-05-18 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_member_count(apps, schema_editor):
    CloseGroup = apps.get_model("core", "CloseGroup")
    CloseGroupMember = apps.get_model("core", "CloseGroupMember")
    for group in CloseGroup.objects.all():
        group.member_count = CloseGroupMember.objects.filter(
            close_group=group, status="JOINED"
        ).count()
        group.save(update_fields=["member_count"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_move_feed_to_feed_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='closegroup',
            name='member_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='closegroup',
            name='name',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='closegroup',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='close_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='closegroup',
            index=models.Index(fields=['name'], name='close_group_name_3b03ad_idx'),
        ),
        migrations.RunPython(backfill_member_count, noop),
    ]
