# Generated by Django 5.2.14 on 2026-05-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_closegroup_member_count_closegroup_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='is_password_updated',
            field=models.BooleanField(default=False),
        ),
    ]
