# Generated by Django 5.2.14 on 2026-06-16 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_usermaster_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userotp',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userotp',
            name='user',
            field=models.ForeignKey(default='2e2423ca-c8f4-4d4b-bc65-9a3bc9d7303c', on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
