# Generated by Django 5.2.14 on 2026-06-16 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_userotp_user_id_userotp_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='otps', to=settings.AUTH_USER_MODEL),
        ),
    ]
