# Generated by Django 5.2.14 on 2026-05-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_usermaster_is_password_updated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membershipapplication',
            old_name='reason',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='membershipapplication',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='membershipapplication',
            name='last_name',
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='membershipapplication',
            name='source',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
