# Generated by Django 5.2.14 on 2026-05-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_reason_membershipapplication_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='status',
            field=models.CharField(choices=[('invited', 'Invited'), ('joined', 'Joined'), ('removed', 'Removed'), ('rejected', 'Rejected')], default='invited', max_length=20),
        ),
    ]
