# Generated by Django 5.2.14 on 2026-05-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_add_rejected_status_to_family_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familymember',
            name='relation',
            field=models.CharField(
                choices=[
                    ('spouse', 'Spouse'),
                    ('mother', 'Mother'),
                    ('father', 'Father'),
                    ('son', 'Son'),
                    ('daughter', 'Daughter'),
                    ('brother', 'Brother'),
                    ('sister', 'Sister'),
                    ('grandfather', 'Grandfather'),
                    ('grandmother', 'Grandmother'),
                    ('grandson', 'Grandson'),
                    ('granddaughter', 'Granddaughter'),
                    ('uncle', 'Uncle'),
                    ('aunt', 'Aunt'),
                    ('nephew', 'Nephew'),
                    ('niece', 'Niece'),
                    ('father_in_law', 'Father-in-law'),
                    ('mother_in_law', 'Mother-in-law'),
                    ('son_in_law', 'Son-in-law'),
                    ('daughter_in_law', 'Daughter-in-law'),
                    ('brother_in_law', 'Brother-in-law'),
                    ('sister_in_law', 'Sister-in-law'),
                    ('stepfather', 'Stepfather'),
                    ('stepmother', 'Stepmother'),
                    ('stepson', 'Stepson'),
                    ('stepdaughter', 'Stepdaughter'),
                    ('stepbrother', 'Stepbrother'),
                    ('stepsister', 'Stepsister'),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
