# Generated by Django 5.2.15 on 2026-08-05 08:52

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_alter_school_primary_color_and_more'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('speed', models.DecimalField(decimal_places=2, default=0, help_text='Speed in km/h', max_digits=5)),
                ('heading', models.PositiveSmallIntegerField(blank=True, help_text='Direction (0–359°)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(359)])),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, help_text='Altitude in meters', max_digits=8, null=True)),
                ('accuracy', models.DecimalField(blank=True, decimal_places=2, help_text='GPS accuracy in meters', max_digits=6, null=True)),
                ('source', models.CharField(choices=[('MOBILE', 'Driver Mobile'), ('GPS_DEVICE', 'GPS Device')], default='MOBILE', max_length=20)),
                ('device_timestamp', models.DateTimeField(blank=True, help_text='Timestamp received from the GPS device/mobile.', null=True)),
                ('recorded_at', models.DateTimeField(db_index=True, help_text='Time when this location was recorded.')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_history', to='school.branch')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='school.school')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='transport.trip')),
            ],
            options={
                'db_table': 'transport_location_history',
                'ordering': ['-recorded_at'],
                'get_latest_by': 'recorded_at',
                'indexes': [models.Index(fields=['trip', '-recorded_at'], name='trip_recorded_idx'), models.Index(fields=['school', '-recorded_at'], name='school_recorded_idx')],
            },
        ),
    ]
