# Generated by Django 5.2.15 on 2026-08-13 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_alter_school_primary_color_and_more'),
        ('transport', '0002_locationhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehicles', to='school.branch'),
        ),
    ]
