# Generated by Django 5.2.15 on 2026-09-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_stop_stop_type_stop_transport_s_stop_ty_b80733_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledocument',
            name='document_type',
            field=models.CharField(choices=[('RC_BOOK', 'RC Book'), ('INSURANCE', 'Insurance'), ('FITNESS', 'Fitness Certificate'), ('POLLUTION', 'Pollution Certificate'), ('PERMIT', 'Permit'), ('ROAD_TAX', 'Road Tax'), ('PHOTO', 'Photo'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
