# Generated by Django 5.2.15 on 2026-09-17 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0005_alter_vehicledocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledocument',
            name='document_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
