# Generated by Django 5.2.15 on 2026-09-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_alter_vehicledocument_document_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='routestop',
            name='distance_from_school',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Distance from school in kilometres', max_digits=6),
        ),
    ]
