# Generated by Django 5.2.15 on 2026-09-21 07:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0011_feecollectionplan_name'),
        ('school', '0037_grade_branch'),
        ('transport', '0007_routestop_distance_from_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportFeeConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_fee_configurations', to='school.academicyear')),
                ('fee_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transport_fee_configurations', to='fee.feetype')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_configurations', to='transport.route')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_fee_configurations', to='school.school')),
            ],
            options={
                'db_table': 'transport_fee_configurations',
            },
        ),
        migrations.CreateModel(
            name='TransportStopSurcharge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('surcharge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('route_stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_fee_surcharges', to='transport.routestop')),
                ('transport_fee_configuration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_surcharges', to='transport.transportfeeconfiguration')),
            ],
            options={
                'db_table': 'transport_stop_surcharges',
            },
        ),
        migrations.AddConstraint(
            model_name='transportfeeconfiguration',
            constraint=models.UniqueConstraint(fields=('academic_year', 'route', 'fee_type'), name='unique_transport_fee_route_type'),
        ),
        migrations.AddConstraint(
            model_name='transportstopsurcharge',
            constraint=models.UniqueConstraint(fields=('transport_fee_configuration', 'route_stop'), name='unique_transport_stop_surcharge'),
        ),
    ]
