# Generated by Django 5.2.15 on 2026-09-25 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0039_schooldocumenttype_unique_school_document_type_color'),
        ('transport', '0008_transportfeeconfiguration_transportstopsurcharge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripStopStatus',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REACHED', 'Reached'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('reached_time', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trip_stop_statuses', to='school.branch')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_stop_statuses', to='school.school')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_statuses', to='transport.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_statuses', to='transport.trip')),
            ],
            options={
                'db_table': 'transport_trip_stop_status',
                'indexes': [models.Index(fields=['trip'], name='transport_t_trip_id_8f57ab_idx'), models.Index(fields=['stop'], name='transport_t_stop_id_8022b9_idx'), models.Index(fields=['status'], name='transport_t_status_b3f371_idx')],
                'constraints': [models.UniqueConstraint(fields=('trip', 'stop'), name='unique_trip_stop_status')],
            },
        ),
    ]
