# Generated by Django 5.2.15 on 2026-09-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_tripstopstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledocument',
            name='document_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
