# Generated by Django 5.2.15 on 2026-09-28 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_alter_vehicledocument_document_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledocument',
            name='document_file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
