# Generated by Django 5.2.15 on 2026-10-08 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0011_alter_vehicledocument_document_file'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='studenttransport',
            name='unique_student_transport',
        ),
    ]
