# Generated by Django 5.2.15 on 2026-06-19 09:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0017_studentdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeCollectionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('plan_type', models.CharField(choices=[('ANNUAL', 'Annual'), ('TERM', 'Term'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('CUSTOM', 'Custom')], max_length=20)),
            ],
            options={
                'db_table': 'fee_collection_plans',
            },
        ),
        migrations.CreateModel(
            name='FeeConcession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=100)),
                ('concession_type', models.CharField(choices=[('FLAT', 'Flat'), ('PERCENTAGE', 'Percentage')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
            options={
                'db_table': 'fee_concessions',
            },
        ),
        migrations.CreateModel(
            name='FeeInstallment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=50)),
                ('due_date', models.DateField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('collection_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='fee.feecollectionplan')),
            ],
            options={
                'db_table': 'fee_installments',
            },
        ),
        migrations.CreateModel(
            name='FeeTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
            options={
                'db_table': 'fee_templates',
            },
        ),
        migrations.AddField(
            model_name='feecollectionplan',
            name='fee_template',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='collection_plan', to='fee.feetemplate'),
        ),
        migrations.CreateModel(
            name='FeeTemplateItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('fee_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fee.feetemplate')),
            ],
            options={
                'db_table': 'fee_template_items',
            },
        ),
        migrations.CreateModel(
            name='FeeInstallmentItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fee.feeinstallment')),
                ('fee_template_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee.feetemplateitem')),
            ],
            options={
                'db_table': 'fee_installment_items',
            },
        ),
        migrations.CreateModel(
            name='FeeType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=100)),
                ('is_optional', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_types', to='school.school')),
            ],
            options={
                'db_table': 'fee_types',
            },
        ),
        migrations.AddField(
            model_name='feetemplateitem',
            name='fee_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee.feetype'),
        ),
        migrations.CreateModel(
            name='LateFeeRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('from_day', models.PositiveIntegerField()),
                ('to_day', models.PositiveIntegerField()),
                ('rule_type', models.CharField(choices=[('FLAT', 'Flat'), ('PER_DAY', 'Per Day'), ('PERCENTAGE', 'Percentage')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('collection_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee.feecollectionplan')),
            ],
            options={
                'db_table': 'late_fee_rules',
            },
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('due_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('scholarship', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('WAIVED', 'Waived')], default='PENDING', max_length=20)),
                ('concession', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fee.feeconcession')),
                ('installment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee.feeinstallmentitem')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
            options={
                'db_table': 'student_fees',
            },
        ),
        migrations.CreateModel(
            name='StudentFeeAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('assigned_date', models.DateField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fee_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fee.feetemplate')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.student')),
            ],
            options={
                'db_table': 'student_fee_assignments',
            },
        ),
        migrations.CreateModel(
            name='StudentFeePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'Upi'), ('CARD', 'Card'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online'), ('NEFT', 'Neft')], max_length=20)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student_fee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='fee.studentfee')),
            ],
            options={
                'db_table': 'student_fee_payments',
            },
        ),
        migrations.AddIndex(
            model_name='feeconcession',
            index=models.Index(fields=['school'], name='fee_concess_school__f86780_idx'),
        ),
        migrations.AddConstraint(
            model_name='feeconcession',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_fee_concession'),
        ),
        migrations.AddIndex(
            model_name='feeinstallment',
            index=models.Index(fields=['collection_plan'], name='fee_install_collect_96086a_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinstallment',
            index=models.Index(fields=['due_date'], name='fee_install_due_dat_1b7aa6_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinstallment',
            index=models.Index(fields=['collection_plan', 'order'], name='fee_install_collect_e29836_idx'),
        ),
        migrations.AddConstraint(
            model_name='feeinstallment',
            constraint=models.UniqueConstraint(fields=('collection_plan', 'name'), name='unique_installment_name'),
        ),
        migrations.AddIndex(
            model_name='feetemplate',
            index=models.Index(fields=['school', 'academic_year'], name='fee_templat_school__c872c5_idx'),
        ),
        migrations.AddIndex(
            model_name='feetemplate',
            index=models.Index(fields=['grade'], name='fee_templat_grade_i_459d6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='feetemplate',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'grade', 'name'), name='unique_fee_template'),
        ),
        migrations.AddIndex(
            model_name='feecollectionplan',
            index=models.Index(fields=['fee_template'], name='fee_collect_fee_tem_d1b31b_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinstallmentitem',
            index=models.Index(fields=['installment'], name='fee_install_install_546bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='feeinstallmentitem',
            index=models.Index(fields=['fee_template_item'], name='fee_install_fee_tem_ebeb23_idx'),
        ),
        migrations.AddConstraint(
            model_name='feeinstallmentitem',
            constraint=models.UniqueConstraint(fields=('installment', 'fee_template_item'), name='unique_installment_fee_item'),
        ),
        migrations.AddIndex(
            model_name='feetype',
            index=models.Index(fields=['school'], name='fee_types_school__f61224_idx'),
        ),
        migrations.AddIndex(
            model_name='feetype',
            index=models.Index(fields=['school', 'name'], name='fee_types_school__89f503_idx'),
        ),
        migrations.AddConstraint(
            model_name='feetype',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_fee_type_per_school'),
        ),
        migrations.AddIndex(
            model_name='feetemplateitem',
            index=models.Index(fields=['fee_template'], name='fee_templat_fee_tem_d2a06c_idx'),
        ),
        migrations.AddIndex(
            model_name='feetemplateitem',
            index=models.Index(fields=['fee_type'], name='fee_templat_fee_typ_ddd2fd_idx'),
        ),
        migrations.AddConstraint(
            model_name='feetemplateitem',
            constraint=models.UniqueConstraint(fields=('fee_template', 'fee_type'), name='unique_fee_template_item'),
        ),
        migrations.AddIndex(
            model_name='latefeerule',
            index=models.Index(fields=['collection_plan'], name='late_fee_ru_collect_d51775_idx'),
        ),
        migrations.AddIndex(
            model_name='latefeerule',
            index=models.Index(fields=['from_day', 'to_day'], name='late_fee_ru_from_da_fb37bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='latefeerule',
            constraint=models.UniqueConstraint(fields=('collection_plan', 'from_day', 'to_day'), name='unique_late_fee_rule'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['student'], name='student_fee_student_6596fa_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['status'], name='student_fee_status_e7bd46_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['due_date'], name='student_fee_due_dat_8d58eb_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfee',
            index=models.Index(fields=['student', 'status'], name='student_fee_student_40a6f5_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.UniqueConstraint(fields=('student', 'installment_item'), name='unique_student_installment_fee'),
        ),
        migrations.AddIndex(
            model_name='studentfeeassignment',
            index=models.Index(fields=['student'], name='student_fee_student_cb63cb_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeeassignment',
            index=models.Index(fields=['fee_template'], name='student_fee_fee_tem_4a5b97_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentfeeassignment',
            constraint=models.UniqueConstraint(fields=('student', 'fee_template'), name='unique_student_fee_assignment'),
        ),
        migrations.AddIndex(
            model_name='studentfeepayment',
            index=models.Index(fields=['student_fee'], name='student_fee_student_492824_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeepayment',
            index=models.Index(fields=['payment_date'], name='student_fee_payment_8d44b2_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeepayment',
            index=models.Index(fields=['receipt_number'], name='student_fee_receipt_ccd470_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeepayment',
            index=models.Index(fields=['transaction_id'], name='student_fee_transac_c29963_idx'),
        ),
        migrations.AddIndex(
            model_name='studentfeepayment',
            index=models.Index(fields=['is_cancelled'], name='student_fee_is_canc_cb2d6c_idx'),
        ),
    ]
