# Generated by Django 5.2.15 on 2026-06-24 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfeeassignment',
            name='concession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fee.feeconcession'),
        ),
    ]
