# Generated by Django 5.2.15 on 2026-06-24 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0004_studentfeeassignment_concession'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfee',
            name='scholarship',
        ),
    ]
