# Generated by Django 5.2.15 on 2026-06-24 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0005_remove_studentfee_scholarship'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfee',
            name='concession',
        ),
    ]
