# Generated by Django 5.2.15 on 2026-06-24 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0007_studentfeepayment_gateway_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SchoolPaymentGateway',
        ),
    ]
