# Generated by Django 5.2.15 on 2026-06-24 11:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0008_delete_schoolpaymentgateway'),
        ('school', '0018_student_aadhaar_number_student_board_student_caste_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolPaymentGateway',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gateway', models.CharField(choices=[('RAZORPAY', 'Razorpay'), ('PHONEPE', 'Phonepe'), ('STRIPE', 'Stripe'), ('PAYTM', 'Paytm'), ('CASHFREE', 'Cashfree')], max_length=50)),
                ('merchant_id', models.CharField(max_length=255)),
                ('api_key', models.CharField(max_length=500)),
                ('secret_key', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
            ],
            options={
                'db_table': 'school_payment_gateways',
                'indexes': [models.Index(fields=['school'], name='school_paym_school__2d1f25_idx'), models.Index(fields=['gateway'], name='school_paym_gateway_5f7bcd_idx'), models.Index(fields=['is_active'], name='school_paym_is_acti_c541f8_idx'), models.Index(fields=['school', 'is_active'], name='school_paym_school__f248f9_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'gateway'), name='unique_school_gateway')],
            },
        ),
    ]
