# Generated by Django 5.2.15 on 2026-09-21 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0009_schoolpaymentgateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollectionplan',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='feeinstallment',
            name='allocation_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
