# Generated by Django 5.2.15 on 2026-09-21 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0010_feecollectionplan_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feecollectionplan',
            name='name',
            field=models.CharField(default='Term Payment Plan', max_length=100),
            preserve_default=False,
        ),
    ]
