# Generated by Django 5.2.15 on 2026-09-22 05:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0011_feecollectionplan_name'),
        ('school', '0037_grade_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plan_type', models.CharField(choices=[('ANNUAL', 'Annual'), ('TERM', 'Term'), ('MONTHLY', 'Monthly'), ('CUSTOM', 'Custom')], default='ANNUAL', max_length=20)),
                ('number_of_terms', models.PositiveSmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'fee_plans',
            },
        ),
        migrations.CreateModel(
            name='FeePlanGrade',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'fee_plan_grades',
            },
        ),
        migrations.CreateModel(
            name='FeePlanInstallment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('installment_number', models.PositiveSmallIntegerField()),
                ('allocation_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
            ],
            options={
                'db_table': 'fee_plan_installments',
            },
        ),
        migrations.RemoveConstraint(
            model_name='feetype',
            name='unique_fee_type_per_school',
        ),
        migrations.RemoveConstraint(
            model_name='studentfee',
            name='unique_student_installment_fee',
        ),
        migrations.RemoveIndex(
            model_name='feetype',
            name='fee_types_school__f61224_idx',
        ),
        migrations.RemoveIndex(
            model_name='feetype',
            name='fee_types_school__89f503_idx',
        ),
        migrations.RemoveIndex(
            model_name='studentfeepayment',
            name='student_fee_receipt_ccd470_idx',
        ),
        migrations.RenameField(
            model_name='feetype',
            old_name='description',
            new_name='note',
        ),
        migrations.RemoveField(
            model_name='studentfee',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='studentfee',
            name='installment_item',
        ),
        migrations.AddField(
            model_name='feetype',
            name='academic_year',
            field=models.ForeignKey(default='3c96936c-c6ce-4d36-be9f-9cdeebb8ff60', on_delete=django.db.models.deletion.PROTECT, related_name='fee_types', to='school.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feetype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='concession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_fees', to='fee.feeconcession'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='concession_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='fee_type',
            field=models.ForeignKey(default='139c5957-99e2-4c28-abfb-be1104bd4bc5', on_delete=django.db.models.deletion.PROTECT, related_name='student_fees', to='fee.feetype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentfee',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='school',
            field=models.ForeignKey(default='2116c83d-0b01-4f9f-9e5d-22412dc6f170', on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='school.school'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentfee',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default='10000', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentfeepayment',
            name='school',
            field=models.ForeignKey(default='2116c83d-0b01-4f9f-9e5d-22412dc6f170', on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_payments', to='school.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='late_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fees', to='school.student'),
        ),
        migrations.AlterField(
            model_name='studentfeepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='studentfeepayment',
            name='collected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_fee_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentfeepayment',
            name='payment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='studentfeepayment',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('CARD', 'Card'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online'), ('NEFT', 'NEFT')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentfeepayment',
            name='receipt_number',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentfeepayment',
            name='student_fee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fee.studentfee'),
        ),
        migrations.AddConstraint(
            model_name='feetype',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'name'), name='unique_fee_type_school_academic_year_name'),
        ),
        migrations.AddConstraint(
            model_name='studentfeepayment',
            constraint=models.UniqueConstraint(fields=('school', 'receipt_number'), name='unique_school_receipt_number'),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_plans', to='school.academicyear'),
        ),
        migrations.AddField(
            model_name='feeplan',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_plans', to='school.school'),
        ),
        migrations.AddField(
            model_name='studentfee',
            name='fee_plan',
            field=models.ForeignKey(default='2116c83d-0b01-4f9f-9e5d-22412dc6f190', on_delete=django.db.models.deletion.PROTECT, related_name='student_fees', to='fee.feeplan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feeplangrade',
            name='fee_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='fee.feeplan'),
        ),
        migrations.AddField(
            model_name='feeplangrade',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_plans', to='school.grade'),
        ),
        migrations.AddField(
            model_name='feeplaninstallment',
            name='fee_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='fee.feeplan'),
        ),
        migrations.AddConstraint(
            model_name='feeplan',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'name'), name='unique_fee_plan'),
        ),
        migrations.AddConstraint(
            model_name='feeplangrade',
            constraint=models.UniqueConstraint(fields=('fee_plan', 'grade'), name='unique_fee_plan_grade'),
        ),
        migrations.AddConstraint(
            model_name='feeplaninstallment',
            constraint=models.UniqueConstraint(fields=('fee_plan', 'installment_number'), name='unique_fee_plan_installment_number'),
        ),
    ]
