# Generated by Django 5.2.15 on 2026-10-06 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0012_feeplan_feeplangrade_feeplaninstallment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feetype',
            name='refund_type',
            field=models.CharField(choices=[('REFUNDABLE', 'Refundable'), ('NON_REFUNDABLE', 'Non Refundable'), ('PARTIALLY_REFUNDABLE', 'Partially Refundable')], default='NON_REFUNDABLE', max_length=30),
        ),
    ]
