# Generated by Django 5.2.15 on 2026-10-06 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0013_feetype_refund_type'),
        ('school', '0039_schooldocumenttype_unique_school_document_type_color'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feecollectionplan',
            name='fee_collect_fee_tem_d1b31b_idx',
        ),
        migrations.RemoveField(
            model_name='feecollectionplan',
            name='fee_template',
        ),
        migrations.AddField(
            model_name='feecollectionplan',
            name='school',
            field=models.ForeignKey(default='2116c83d-0b01-4f9f-9e5d-22412dc6f170', on_delete=django.db.models.deletion.CASCADE, related_name='fee_collection_plans', to='school.school'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='feecollectionplan',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_fee_collection_plan'),
        ),
    ]
