# Generated by Django 5.2.15 on 2026-10-06 11:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0014_remove_feecollectionplan_fee_collect_fee_tem_d1b31b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeTemplateCollectionPlan',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collection_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_mappings', to='fee.feecollectionplan')),
                ('fee_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_plan_mappings', to='fee.feetemplate')),
            ],
            options={
                'db_table': 'fee_template_collection_plans',
                'indexes': [models.Index(fields=['fee_template'], name='fee_templat_fee_tem_c480e3_idx'), models.Index(fields=['collection_plan'], name='fee_templat_collect_5a5108_idx')],
                'constraints': [models.UniqueConstraint(fields=('fee_template', 'collection_plan'), name='unique_fee_template_collection_plan')],
            },
        ),
    ]
