# Generated by Django 5.2.15 on 2026-10-06 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0015_feetemplatecollectionplan'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='feetemplatecollectionplan',
            name='fee_templat_fee_tem_c480e3_idx',
        ),
        migrations.RemoveIndex(
            model_name='feetemplatecollectionplan',
            name='fee_templat_collect_5a5108_idx',
        ),
    ]
