# Generated by Django 5.2.15 on 2026-10-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0016_remove_feetemplatecollectionplan_fee_templat_fee_tem_c480e3_idx_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='latefeerule',
            name='unique_late_fee_rule',
        ),
        migrations.RemoveIndex(
            model_name='latefeerule',
            name='late_fee_ru_collect_d51775_idx',
        ),
        migrations.RemoveField(
            model_name='latefeerule',
            name='collection_plan',
        ),
        migrations.AddField(
            model_name='latefeerule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='latefeerule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='latefeerule',
            name='is_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='latefeerule',
            constraint=models.UniqueConstraint(fields=('from_day', 'to_day'), name='unique_late_fee_rule'),
        ),
    ]
