# Generated by Django 5.2.15 on 2026-10-07 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0017_remove_latefeerule_unique_late_fee_rule_and_more'),
        ('school', '0039_schooldocumenttype_unique_school_document_type_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='latefeerule',
            name='school',
            field=models.ForeignKey(default='2116c83d-0b01-4f9f-9e5d-22412dc6f170', on_delete=django.db.models.deletion.CASCADE, related_name='late_fee_rules', to='school.school'),
            preserve_default=False,
        ),
    ]
