# Generated by Django 5.2.15 on 2026-10-07 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0018_latefeerule_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentfee',
            name='fee_plan',
        ),
        migrations.AddField(
            model_name='studentfee',
            name='fee_template',
            field=models.ForeignKey(default='097269a8-9f4a-43ae-bf9b-1229ab054ed0', on_delete=django.db.models.deletion.PROTECT, related_name='student_fees', to='fee.feetemplate'),
            preserve_default=False,
        ),
    ]
