# Generated by Django 5.2.15 on 2026-10-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0019_remove_studentfee_fee_plan_studentfee_fee_template'),
        ('school', '0039_schooldocumenttype_unique_school_document_type_color'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='studentfee',
            constraint=models.UniqueConstraint(fields=('student', 'fee_template', 'fee_type'), name='unique_student_fee'),
        ),
    ]
