# Generated by Django 5.2.15 on 2026-10-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0020_studentfee_unique_student_fee'),
        ('school', '0039_schooldocumenttype_unique_school_document_type_color'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='latefeerule',
            name='unique_late_fee_rule',
        ),
        migrations.AddConstraint(
            model_name='latefeerule',
            constraint=models.UniqueConstraint(fields=('from_day', 'to_day', 'school'), name='unique_late_fee_rule'),
        ),
    ]
