# Generated by Django 5.2.15 on 2026-10-09 12:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fee', '0021_remove_latefeerule_unique_late_fee_rule_and_more'),
        ('school', '0039_schooldocumenttype_unique_school_document_type_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFeeSummary',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_concession', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_late_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_fee_summaries', to='school.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fee_summaries', to='school.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_summaries', to='school.student')),
            ],
            options={
                'db_table': 'student_fee_summaries',
                'indexes': [models.Index(fields=['school', 'academic_year'], name='student_fee_school__0eeea8_idx'), models.Index(fields=['student'], name='student_fee_student_feb9b5_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'student', 'academic_year'), name='unique_student_fee_summary_per_year')],
            },
        ),
    ]
