# Generated by Django 5.2.14 on 2026-05-28 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoollead',
            name='contact_person',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='schoollead',
            name='email',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='schoollead',
            name='number_of_students',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
