# Generated by Django 5.2.14 on 2026-05-28 09:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_schoollead_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoollead',
            name='created_by',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='schoollead',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoollead',
            name='is_mobile_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoollead',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoollead',
            name='updated_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schoollead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='schoollead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('board', models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('STATE', 'State Board'), ('INTERNATIONAL', 'International'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('principal_name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_students', models.PositiveIntegerField(default=0)),
                ('total_staff', models.PositiveIntegerField(default=0)),
                ('established_year', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
            ],
            options={
                'db_table': 'schools',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='schools_code_adc256_idx'), models.Index(fields=['email'], name='schools_email_63ca61_idx'), models.Index(fields=['phone_number'], name='schools_phone_n_0325f6_idx')],
            },
        ),
    ]
