# Generated by Django 5.2.14 on 2026-05-30 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_schoollead_created_by_schoollead_is_email_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoollead',
            name='status',
            field=models.CharField(choices=[('lead', 'Lead'), ('subscribed', 'Subscribed')], default='lead', max_length=20),
        ),
    ]
