# Generated by Django 5.2.14 on 2026-06-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_schoollead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
