# Generated by Django 5.2.14 on 2026-06-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_alter_school_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='schoollead',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
