# Generated by Django 5.2.14 on 2026-06-08 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_branch_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='principal_email',
            field=models.CharField(blank=True, null=True),
        ),
    ]
