# Generated by Django 5.2.14 on 2026-06-05 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_branch_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='school.organization'),
        ),
    ]
