# Generated by Django 5.2.14 on 2026-06-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_school_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='school',
        ),
        migrations.RemoveField(
            model_name='school',
            name='organization',
        ),
        migrations.RemoveIndex(
            model_name='school',
            name='schools_organiz_566a1a_idx',
        ),
        migrations.RemoveField(
            model_name='school',
            name='principal_email',
        ),
        migrations.RemoveField(
            model_name='school',
            name='principal_mobile',
        ),
        migrations.AddField(
            model_name='school',
            name='total_staff',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='school',
            name='total_students',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['email'], name='schools_email_63ca61_idx'),
        ),
        migrations.AddIndex(
            model_name='school',
            index=models.Index(fields=['phone_number'], name='schools_phone_n_0325f6_idx'),
        ),
        migrations.DeleteModel(
            name='Branch',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
