# Generated by Django 5.2.14 on 2026-06-09 07:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_school_principal_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='website',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='school.school')),
            ],
            options={
                'db_table': 'academic_years',
                'indexes': [models.Index(fields=['school'], name='academic_ye_school__fa7c5a_idx'), models.Index(fields=['status'], name='academic_ye_status_398bb4_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'name'), name='unique_school_academic_year')],
            },
        ),
    ]
