# Generated by Django 5.2.14 on 2026-06-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_alter_organization_logo_alter_organization_website_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='website',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
