# Generated by Django 5.2.14 on 2026-06-12 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
    ]
