# Generated by Django 5.2.14 on 2026-06-12 10:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_remove_student_father_remove_student_guardian_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('AADHAAR', 'Aadhaar Card'), ('PHOTO', 'Photo'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('TRANSFER_CERTIFICATE', 'Transfer Certificate'), ('BONAFIDE', 'Bonafide Certificate'), ('ACADEMIC_RECORD', 'Academic Record'), ('ID_CARD', 'ID Card'), ('OTHER', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=500)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.academicyear')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='school.student')),
            ],
            options={
                'db_table': 'student_documents',
                'indexes': [models.Index(fields=['student'], name='student_doc_student_23b985_idx'), models.Index(fields=['document_type'], name='student_doc_documen_b0ff04_idx')],
            },
        ),
    ]
