# Generated by Django 5.2.15 on 2026-06-24 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_studentdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhaar_number',
            field=models.CharField(blank=True, db_index=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='board',
            field=models.CharField(choices=[('STATE', 'State'), ('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('IB', 'IB'), ('IGCSE', 'IGCSE'), ('NIOS', 'NIOS'), ('OTHER', 'Other')], db_index=True, default='STATE', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='caste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_type',
            field=models.CharField(choices=[('NEW', 'New Admission'), ('TRANSFER', 'Transfer'), ('RE_ADMISSION', 'Re Admission')], default='NEW', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='hostel_type',
            field=models.CharField(choices=[('DAY_SCHOLAR', 'Day Scholar'), ('HOSTELLER', 'Hosteller')], default='DAY_SCHOLAR', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='identification_marks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='Indian', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='photo_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='pickup_point',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='place_of_birth',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_exam_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='previous_school_tc_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='sub_caste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='transport_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['board'], name='students_board_4b9baa_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['school', 'academic_year'], name='students_school__dafb30_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['grade', 'section'], name='students_grade_i_81d959_idx'),
        ),
    ]
