# Generated by Django 5.2.15 on 2026-06-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_student_aadhaar_number_student_board_student_caste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='primary_color',
            field=models.CharField(default='FFFFFF', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='secondary_color',
            field=models.CharField(default='FFFFFF', max_length=100),
        ),
    ]
