# Generated by Django 5.2.15 on 2026-06-30 05:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_school_primary_color_school_secondary_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolConfiguration',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('backoffice_url', models.URLField(blank=True, max_length=500, null=True)),
                ('api_base_url', models.URLField(blank=True, max_length=500, null=True)),
                ('parent_android_package', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_android_version', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_playstore_url', models.URLField(blank=True, max_length=500, null=True)),
                ('parent_android_force_update', models.BooleanField(default=False)),
                ('parent_ios_bundle', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_ios_version', models.CharField(blank=True, max_length=20, null=True)),
                ('parent_appstore_url', models.URLField(blank=True, max_length=500, null=True)),
                ('parent_ios_force_update', models.BooleanField(default=False)),
                ('admin_android_package', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_android_version', models.CharField(blank=True, max_length=20, null=True)),
                ('admin_playstore_url', models.URLField(blank=True, max_length=500, null=True)),
                ('admin_android_force_update', models.BooleanField(default=False)),
                ('admin_ios_bundle', models.CharField(blank=True, max_length=255, null=True)),
                ('admin_ios_version', models.CharField(blank=True, max_length=20, null=True)),
                ('admin_appstore_url', models.URLField(blank=True, max_length=500, null=True)),
                ('admin_ios_force_update', models.BooleanField(default=False)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('favicon_url', models.URLField(blank=True, max_length=500, null=True)),
                ('primary_color', models.CharField(default='#2563EB', max_length=20)),
                ('secondary_color', models.CharField(default='#FFFFFF', max_length=20)),
                ('support_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('support_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='school.school')),
            ],
            options={
                'db_table': 'school_configuration',
            },
        ),
    ]
