# Generated by Django 5.2.15 on 2026-06-30 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_schoolconfiguration'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='schoolconfiguration',
            index=models.Index(fields=['website_url'], name='school_conf_website_ff9fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolconfiguration',
            index=models.Index(fields=['backoffice_url'], name='school_conf_backoff_7c46c6_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolconfiguration',
            index=models.Index(fields=['parent_android_package'], name='school_conf_parent__c767ae_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolconfiguration',
            index=models.Index(fields=['parent_ios_bundle'], name='school_conf_parent__2ba743_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolconfiguration',
            index=models.Index(fields=['admin_android_package'], name='school_conf_admin_a_ee554b_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolconfiguration',
            index=models.Index(fields=['admin_ios_bundle'], name='school_conf_admin_i_17cdbe_idx'),
        ),
    ]
