# Generated by Django 5.2.15 on 2026-06-30 07:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_schoolconfiguration_school_conf_website_ff9fa6_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolClient',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_type', models.CharField(choices=[('WEBSITE', 'Website'), ('BACKOFFICE', 'Backoffice'), ('PARENT_ANDROID', 'Parent Android'), ('PARENT_IOS', 'Parent iOS'), ('ADMIN_ANDROID', 'Admin Android'), ('ADMIN_IOS', 'Admin iOS')], max_length=30)),
                ('identifier', models.CharField(db_index=True, help_text='Website URL, Backoffice URL, Android Package or iOS Bundle Identifier', max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'school_client',
            },
        ),
        migrations.RemoveIndex(
            model_name='schoolconfiguration',
            name='school_conf_website_ff9fa6_idx',
        ),
        migrations.RemoveIndex(
            model_name='schoolconfiguration',
            name='school_conf_backoff_7c46c6_idx',
        ),
        migrations.RemoveIndex(
            model_name='schoolconfiguration',
            name='school_conf_parent__c767ae_idx',
        ),
        migrations.RemoveIndex(
            model_name='schoolconfiguration',
            name='school_conf_parent__2ba743_idx',
        ),
        migrations.RemoveIndex(
            model_name='schoolconfiguration',
            name='school_conf_admin_a_ee554b_idx',
        ),
        migrations.RemoveIndex(
            model_name='schoolconfiguration',
            name='school_conf_admin_i_17cdbe_idx',
        ),
        migrations.RemoveField(
            model_name='schoolconfiguration',
            name='admin_android_package',
        ),
        migrations.RemoveField(
            model_name='schoolconfiguration',
            name='admin_ios_bundle',
        ),
        migrations.RemoveField(
            model_name='schoolconfiguration',
            name='parent_android_package',
        ),
        migrations.RemoveField(
            model_name='schoolconfiguration',
            name='parent_ios_bundle',
        ),
        migrations.AddField(
            model_name='schoolclient',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='school.school'),
        ),
        migrations.AddIndex(
            model_name='schoolclient',
            index=models.Index(fields=['school'], name='school_clie_school__9c16ae_idx'),
        ),
        migrations.AddIndex(
            model_name='schoolclient',
            index=models.Index(fields=['client_type'], name='school_clie_client__670107_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolclient',
            constraint=models.UniqueConstraint(fields=('school', 'client_type'), name='unique_school_client_type'),
        ),
    ]
