# Generated by Django 5.2.15 on 2026-06-30 10:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_schoolclient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(max_length=50)),
                ('staff_type', models.CharField(choices=[('TEACHER', 'Teacher'), ('DRIVER', 'Driver'), ('ACCOUNTANT', 'Accountant'), ('RECEPTIONIST', 'Receptionist'), ('LIBRARIAN', 'Librarian'), ('PRINCIPAL', 'Principal'), ('ADMIN', 'Admin'), ('OFFICE_STAFF', 'Office Staff'), ('SECURITY', 'Security'), ('ATTENDER', 'Attender'), ('LAB_ASSISTANT', 'Lab Assistant'), ('TRANSPORT_MANAGER', 'Transport Manager')], max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('qualification', models.CharField(blank=True, max_length=255, null=True)),
                ('experience', models.DecimalField(decimal_places=1, default=0, max_digits=5)),
                ('joining_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('RESIGNED', 'Resigned'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='school.school')),
            ],
            options={
                'db_table': 'staff',
                'indexes': [models.Index(fields=['school'], name='staff_school__d43fd7_idx'), models.Index(fields=['staff_type'], name='staff_staff_t_63efc1_idx'), models.Index(fields=['status'], name='staff_status_c91b08_idx'), models.Index(fields=['mobile'], name='staff_mobile_cc71da_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'employee_id'), name='unique_staff_employee_id')],
            },
        ),
    ]
