# Generated by Django 5.2.15 on 2026-06-30 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('DRIVER', 'Driver'), ('PRINCIPAL', 'Principal'), ('ADMIN', 'Admin')], max_length=30),
        ),
    ]
