# Generated by Django 5.2.15 on 2026-07-02 11:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_staff_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('AADHAAR', 'Aadhaar'), ('PAN', 'PAN'), ('DRIVING_LICENSE', 'Driving License'), ('PASSPORT', 'Passport'), ('PHOTO', 'Photo'), ('RESUME', 'Resume'), ('QUALIFICATION_CERTIFICATE', 'Qualification Certificate'), ('EXPERIENCE_CERTIFICATE', 'Experience Certificate'), ('MEDICAL_CERTIFICATE', 'Medical Certificate'), ('POLICE_VERIFICATION', 'Police Verification'), ('CONTRACT', 'Contract'), ('OTHER', 'Other')], max_length=50)),
                ('document_name', models.CharField(max_length=255)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('document_url', models.URLField(max_length=500)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='school.staff')),
            ],
            options={
                'db_table': 'staff_documents',
                'indexes': [models.Index(fields=['staff'], name='staff_docum_staff_i_4d5180_idx'), models.Index(fields=['document_type'], name='staff_docum_documen_3bc302_idx'), models.Index(fields=['expiry_date'], name='staff_docum_expiry__5ce5f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('staff', 'document_type'), name='unique_staff_document_type')],
            },
        ),
    ]
