# Generated by Django 5.2.15 on 2026-07-03 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_staffdocument'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='section',
            name='unique_section_per_grade',
        ),
        migrations.AddField(
            model_name='section',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sections', to='school.branch'),
        ),
        migrations.AddField(
            model_name='staff',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffs', to='school.branch'),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school.branch'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', False)), fields=('grade', 'branch', 'name'), name='unique_section_per_grade_branch'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(condition=models.Q(('branch__isnull', True)), fields=('grade', 'name'), name='unique_section_per_grade_without_branch'),
        ),
    ]
