# Generated by Django 5.2.15 on 2026-07-14 10:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_remove_section_unique_section_per_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='school.academicyear')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='school.branch')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='school.school')),
            ],
            options={
                'db_table': 'subjects',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubjectGrade',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_subjects', to='school.grade')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_grades', to='school.subject')),
            ],
            options={
                'db_table': 'subject_grades',
            },
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school'], name='subjects_school__01dc27_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['academic_year'], name='subjects_academi_6ef194_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['branch'], name='subjects_branch__58ca02_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['status'], name='subjects_status_6bd3b8_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school', 'academic_year'], name='subjects_school__7f57df_idx'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['school', 'branch'], name='subjects_school__89b9a2_idx'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'name'), name='unique_subject_per_school'),
        ),
        migrations.AddIndex(
            model_name='subjectgrade',
            index=models.Index(fields=['subject'], name='subject_gra_subject_6861fe_idx'),
        ),
        migrations.AddIndex(
            model_name='subjectgrade',
            index=models.Index(fields=['grade'], name='subject_gra_grade_i_b83f4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='subjectgrade',
            constraint=models.UniqueConstraint(fields=('subject', 'grade'), name='unique_subject_grade'),
        ),
    ]
