# Generated by Django 5.2.15 on 2026-07-28 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_subject_subjectgrade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('DRIVER', 'Driver'), ('BUS_ATTENDANT', 'Bus Attendant'), ('PRINCIPAL', 'Principal'), ('ADMIN', 'Admin')], max_length=30),
        ),
    ]
