# Generated by Django 5.2.15 on 2026-07-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_alter_staff_staff_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
