# Generated by Django 5.2.15 on 2026-07-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_alter_organization_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='primary_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='secondary_color',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
