# Generated by Django 5.2.15 on 2026-09-01 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_schooldocumenttype_schooldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldocumenttype',
            name='school',
            field=models.ForeignKey(default='2116c83d-0b01-4f9f-9e5d-22412dc6f170', on_delete=django.db.models.deletion.CASCADE, related_name='document_types', to='school.school'),
            preserve_default=False,
        ),
    ]
