# Generated by Django 5.2.15 on 2026-09-01 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_schooldocumenttype_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooldocument',
            name='published_at',
        ),
    ]
