# Generated by Django 5.2.15 on 2026-09-02 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0035_remove_schooldocument_published_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schooldocumenttype',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='schooldocumenttype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='schooldocumenttype',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_school_document_type_name'),
        ),
    ]
