# Generated by Django 5.2.15 on 2026-09-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0037_grade_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooldocumenttype',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=20),
        ),
    ]
