# Generated by Django 5.2.15 on 2026-09-22 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0038_schooldocumenttype_color'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schooldocumenttype',
            constraint=models.UniqueConstraint(fields=('school', 'color'), name='unique_school_document_type_color'),
        ),
    ]
