name: Local
variables:
  - name: base_url
    value: http://localhost:8000/
  - name: email
    value: admin@schoolfirst.us
  - name: password
    value: Admin@123
  - name: folder_id
    value: ""
  - name: file_id
    value: ""
  - name: share_id
    value: ""
  - name: thread_id
    value: ""
  - name: invite_code
    value: M70VH1
  - name: member_id
    value: 9b0b2ac4-a437-4080-838b-2b6d6f23d01a
  - name: family_id
    value: 2f1dfc23-2e4f-4adb-967e-65164b30fb80
  - name: user_id
    value: b7dce1c0-5847-4a11-bd3e-fd094eeedc49
  - name: task_id
    value: 391de0cd-604c-415f-ad18-57eff9e71dad
  - name: event_id
    value: 14963a98-f93d-4b09-ae33-9c6e9980790c
