name: Production
variables:
  - name: base_url
    value: https://api.schoolfirst.us/
  - name: email
    value: admin@schoolfirst.us
  - name: password
    value: secure_password
  - name: folder_id
    value: ""
  - name: file_id
    value: ""
  - name: share_id
    value: ""
  - name: thread_id
    value: ""
  - name: invite_code
    value: ""
  - name: member_id
    value: ""
  - name: family_id
    value: ""
