# Generated by Django 5.2.14 on 2026-05-09 04:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thread_id', models.UUIDField(db_index=True, help_text='ID of the thread')),
                ('message_id', models.UUIDField(db_index=True, help_text='ID of the message this attachment belongs to')),
                ('file_path', models.CharField(help_text='Storage path of the file', max_length=500)),
                ('file_name', models.CharField(help_text='Original file name', max_length=255)),
                ('file_size', models.BigIntegerField(help_text='File size in bytes')),
                ('mime_type', models.CharField(help_text='MIME type of the file', max_length=100)),
                ('width', models.IntegerField(help_text='Image/video width in pixels', null=True)),
                ('height', models.IntegerField(help_text='Image/video height in pixels', null=True)),
                ('duration', models.IntegerField(help_text='Audio/video duration in seconds', null=True)),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
                'db_table': 'attachment',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['thread_id', 'message_id'], name='attachment_thread__c6248d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thread_id', models.UUIDField(help_text='ID of the thread this message belongs to')),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], default='user', help_text='Sender type', max_length=10)),
                ('content_blocks', models.JSONField(help_text='Typed content block array (tool_call, text)', null=True)),
                ('schema_version', models.CharField(default='2.0', help_text='Content block schema version', max_length=10)),
                ('role_metadata', models.JSONField(help_text='Assistant-only metadata: stop_reason, model, usage', null=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'message',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['thread_id'], name='message_thread__55c64b_idx'), models.Index(fields=['sender_type'], name='message_sender__d5fae8_idx'), models.Index(fields=['created_at'], name='message_created_19da1c_idx'), models.Index(fields=['thread_id', '-created_at'], name='message_thread__cc928c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Thread ID', primary_key=True, serialize=False)),
                ('user_id', models.UUIDField(db_index=True, help_text='ID of the user who owns this thread')),
                ('name', models.CharField(default='New Chat', help_text='Thread name', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived'), ('DELETED', 'Deleted')], default='ACTIVE', help_text='Thread status', max_length=20)),
                ('summary', models.TextField(help_text='Auto-generated thread summary', null=True)),
                ('model', models.CharField(help_text='LLM model ID used in this thread', max_length=200, null=True)),
                ('settings', models.JSONField(help_text='Per-thread feature flags e.g. {"enabled_web_search": true}', null=True)),
                ('module_settings', models.JSONField(help_text='Module specific settings e.g. {"module_name": "docusafe"}', null=True)),
                ('is_temporary', models.BooleanField(default=False, help_text='Temporary chats excluded from history (e.g., for one-off tasks)')),
            ],
            options={
                'verbose_name': 'Thread',
                'verbose_name_plural': 'Threads',
                'db_table': 'thread',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id', 'status'], name='thread_user_id_1a5503_idx'), models.Index(fields=['created_at'], name='thread_created_a620d1_idx'), models.Index(fields=['user_id', '-created_at'], name='thread_user_id_f27b02_idx')],
            },
        ),
    ]
