# Generated by Django 5.2.14 on 2026-05-09 04:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocusafeFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder_id', models.UUIDField()),
                ('owner_id', models.UUIDField()),
                ('file_name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('file_path', models.CharField(max_length=1024)),
                ('mime_type', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField()),
                ('file_extension', models.CharField(max_length=50)),
                ('checksum', models.CharField(max_length=128, null=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=50)),
                ('llm_status', models.CharField(choices=[('PENDING', 'Pending'), ('NOT_SUPPORTED', 'Not Supported'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=50)),
                ('summary', models.TextField(null=True)),
                ('embedding_model', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'DocusafeFile',
                'verbose_name_plural': 'DocusafeFiles',
                'db_table': 'docusafe_file',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['folder_id'], name='docusafe_fi_folder__ed32d1_idx'), models.Index(fields=['mime_type'], name='docusafe_fi_mime_ty_57e01e_idx'), models.Index(fields=['is_shared'], name='docusafe_fi_is_shar_051bf1_idx')],
                'unique_together': {('folder_id', 'file_name')},
            },
        ),
        migrations.CreateModel(
            name='DocusafeFileAccess',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_id', models.UUIDField()),
                ('access_type', models.CharField(choices=[('FAMILY', 'Family'), ('USER', 'User')], default='FAMILY', max_length=10)),
                ('family_id', models.UUIDField()),
                ('user_id', models.UUIDField(null=True)),
                ('owner_id', models.UUIDField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'DocusafeFileAccess',
                'verbose_name_plural': 'DocusafeFileAccesses',
                'db_table': 'docusafe_file_access',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file_id'], name='docusafe_fi_file_id_c5bb17_idx'), models.Index(fields=['access_type'], name='docusafe_fi_access__efe7c6_idx'), models.Index(fields=['family_id'], name='docusafe_fi_family__8be09c_idx'), models.Index(fields=['user_id'], name='docusafe_fi_user_id_27ff07_idx'), models.Index(fields=['owner_id'], name='docusafe_fi_owner_i_d03770_idx'), models.Index(fields=['is_active'], name='docusafe_fi_is_acti_5a9521_idx')],
                'unique_together': {('file_id', 'access_type', 'family_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='DocusafeFolder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('owner_id', models.UUIDField()),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('total_size', models.BigIntegerField(default=0)),
                ('is_shared', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DELETED', 'Deleted')], default='ACTIVE', max_length=50)),
            ],
            options={
                'verbose_name': 'DocusafeFolder',
                'verbose_name_plural': 'DocusafeFolders',
                'db_table': 'docusafe_folder',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner_id'], name='docusafe_fo_owner_i_afc01d_idx'), models.Index(fields=['created_by'], name='docusafe_fo_created_5d97d5_idx'), models.Index(fields=['is_shared'], name='docusafe_fo_is_shar_63af20_idx')],
                'unique_together': {('owner_id', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ShareViewLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_id', models.UUIDField()),
                ('success', models.BooleanField()),
                ('failure_reason', models.CharField(max_length=100, null=True)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('device_type', models.CharField(max_length=50, null=True)),
                ('device_os', models.CharField(max_length=100, null=True)),
                ('browser', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('client_metadata', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'ShareViewLog',
                'verbose_name_plural': 'ShareViewLogs',
                'db_table': 'docusafe_share_view_log',
                'indexes': [models.Index(fields=['share_id'], name='docusafe_sh_share_i_56d9cd_idx'), models.Index(fields=['viewed_at'], name='docusafe_sh_viewed__e68e95_idx'), models.Index(fields=['ip_address'], name='docusafe_sh_ip_addr_9a778d_idx'), models.Index(fields=['success'], name='docusafe_sh_success_92a475_idx')],
            },
        ),
        migrations.CreateModel(
            name='TemporaryFileShare',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'InActive'), ('EXPIRED', 'Expired'), ('BLOCKED', 'Blocked')], default='ACTIVE', max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('max_views', models.PositiveIntegerField(null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('failed_attempts', models.PositiveIntegerField(default=0)),
                ('max_failed_attempts', models.PositiveIntegerField(default=5)),
                ('title', models.CharField(max_length=255, null=True)),
                ('file_count', models.PositiveIntegerField(default=0)),
                ('owner_id', models.UUIDField()),
                ('recipient_emails', models.JSONField(default=list, null=True)),
            ],
            options={
                'verbose_name': 'TemporaryFileShare',
                'verbose_name_plural': 'TemporaryFileShares',
                'db_table': 'docusafe_temporary_share',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='docusafe_te_status_41d733_idx'), models.Index(fields=['expires_at'], name='docusafe_te_expires_5df189_idx'), models.Index(fields=['owner_id'], name='docusafe_te_owner_i_80ee28_idx')],
            },
        ),
        migrations.CreateModel(
            name='TemporaryShareFile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_id', models.UUIDField()),
                ('file_id', models.UUIDField()),
            ],
            options={
                'verbose_name': 'TemporaryShareFile',
                'verbose_name_plural': 'TemporaryShareFiles',
                'db_table': 'docusafe_temporary_share_file',
                'indexes': [models.Index(fields=['share_id'], name='docusafe_te_share_i_e6bec1_idx'), models.Index(fields=['file_id'], name='docusafe_te_file_id_793cee_idx')],
                'unique_together': {('share_id', 'file_id')},
            },
        ),
    ]
