# Generated by Django 6.0.5 on 2026-05-10 17:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('parent_type', models.CharField(choices=[('event', 'Event'), ('task', 'Task')], max_length=20)),
                ('parent_id', models.UUIDField()),
                ('user_id', models.UUIDField(db_index=True)),
                ('body', models.TextField()),
                ('deleted_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'calendar_comment',
                'indexes': [models.Index(fields=['parent_type', 'parent_id'], name='calendar_co_parent__a2990c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('access_type', models.CharField(choices=[('only_me', 'Only Me'), ('group', 'Group'), ('specific', 'Specific')], default='group', max_length=20)),
                ('access_family_ids', models.JSONField(default=list, null=True)),
                ('access_close_group', models.BooleanField(default=False)),
                ('access_user_ids', models.JSONField(default=list, null=True)),
                ('rrule', models.JSONField(null=True)),
                ('recurrence_date', models.DateField(null=True)),
                ('is_deleted_instance', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creator_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('event_type', models.CharField(max_length=100, null=True)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('reminder_datetime', models.DateTimeField(null=True)),
                ('reminder_types', models.JSONField(null=True)),
                ('location', models.JSONField(null=True)),
                ('attachments', models.JSONField(null=True)),
                ('parent_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='calendar.event')),
            ],
            options={
                'db_table': 'calendar_event',
                'indexes': [models.Index(fields=['start_at'], name='calendar_ev_start_a_7b4e92_idx'), models.Index(fields=['end_at'], name='calendar_ev_end_at_e905a9_idx'), models.Index(fields=['creator_id'], name='calendar_ev_creator_d0109f_idx'), models.Index(fields=['access_type'], name='calendar_ev_access__25e2fd_idx')],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('access_type', models.CharField(choices=[('only_me', 'Only Me'), ('group', 'Group'), ('specific', 'Specific')], default='group', max_length=20)),
                ('access_family_ids', models.JSONField(default=list, null=True)),
                ('access_close_group', models.BooleanField(default=False)),
                ('access_user_ids', models.JSONField(default=list, null=True)),
                ('rrule', models.JSONField(null=True)),
                ('recurrence_date', models.DateField(null=True)),
                ('is_deleted_instance', models.BooleanField(default=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('creator_id', models.UUIDField(db_index=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('task_type', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('wip', 'WIP'), ('done', 'Done')], default='pending', max_length=20)),
                ('done_by', models.UUIDField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('acknowledged_at', models.DateTimeField(null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='routine', max_length=20)),
                ('agent_assist', models.BooleanField(default=False)),
                ('deadline_datetime', models.DateTimeField(null=True)),
                ('reminder_datetime', models.DateTimeField(null=True)),
                ('reminder_types', models.JSONField(null=True)),
                ('location', models.JSONField(null=True)),
                ('attachments', models.JSONField(null=True)),
                ('parent_task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='calendar.task')),
            ],
            options={
                'db_table': 'calendar_task',
                'indexes': [models.Index(fields=['deadline_datetime'], name='calendar_ta_deadlin_b98916_idx'), models.Index(fields=['creator_id'], name='calendar_ta_creator_798610_idx'), models.Index(fields=['status'], name='calendar_ta_status_397129_idx'), models.Index(fields=['is_visible'], name='calendar_ta_is_visi_a17cc3_idx'), models.Index(fields=['access_type'], name='calendar_ta_access__3cfcb4_idx')],
            },
        ),
    ]
