# Generated by Django 5.2.15 on 2026-07-13 11:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0028_remove_section_unique_section_per_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(choices=[('PTM', 'Parent Teacher Meeting'), ('FEE', 'Fee Due'), ('EXAM', 'Exam'), ('HOLIDAY', 'Holiday'), ('EVENT', 'School Event'), ('ANNOUNCEMENT', 'Announcement'), ('HOMEWORK', 'Homework'), ('ASSIGNMENT', 'Assignment'), ('TRANSPORT', 'Transport'), ('LIBRARY', 'Library'), ('OTHER', 'Other')], max_length=30)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('reference_id', models.UUIDField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='school.school')),
            ],
            options={
                'db_table': 'calendar_events',
                'ordering': ['event_date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEventTarget',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('SCHOOL', 'School'), ('BRANCH', 'Branch'), ('GRADE', 'Grade'), ('SECTION', 'Section'), ('STUDENT', 'Student'), ('STAFF', 'Staff')], max_length=20)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_targets', to='school.academicyear')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_targets', to='school.branch')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to='calendar.calendarevent')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_targets', to='school.grade')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_targets', to='school.section')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_targets', to='school.staff')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendar_targets', to='school.student')),
            ],
            options={
                'db_table': 'calendar_event_targets',
            },
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['school', 'event_date'], name='calendar_ev_school__00a1dc_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['event_type'], name='calendar_ev_event_t_25cdb4_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarevent',
            index=models.Index(fields=['status'], name='calendar_ev_status_453150_idx'),
        ),
        migrations.AddIndex(
            model_name='calendareventtarget',
            index=models.Index(fields=['target_type'], name='calendar_ev_target__174db7_idx'),
        ),
        migrations.AddIndex(
            model_name='calendareventtarget',
            index=models.Index(fields=['branch'], name='calendar_ev_branch__f4002d_idx'),
        ),
        migrations.AddIndex(
            model_name='calendareventtarget',
            index=models.Index(fields=['grade'], name='calendar_ev_grade_i_f536c9_idx'),
        ),
        migrations.AddIndex(
            model_name='calendareventtarget',
            index=models.Index(fields=['section'], name='calendar_ev_section_98ef38_idx'),
        ),
        migrations.AddIndex(
            model_name='calendareventtarget',
            index=models.Index(fields=['student'], name='calendar_ev_student_075f90_idx'),
        ),
        migrations.AddIndex(
            model_name='calendareventtarget',
            index=models.Index(fields=['staff'], name='calendar_ev_staff_i_a34922_idx'),
        ),
    ]
