# Generated by Django 6.0.5 on 2026-05-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='recurrence_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_end_date',
            field=models.DateField(null=True),
        ),
    ]
