# Generated by Django 6.0.5 on 2026-05-12 17:27

from django.db import migrations, models
from django.db.models import Count


def backfill_calendar_comment_counts_and_statuses(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Comment = apps.get_model("calendar", "Comment")
    Event = apps.get_model("calendar", "Event")
    Task = apps.get_model("calendar", "Task")

    Task.objects.using(db_alias).filter(status="wip").update(status="pending")

    Event.objects.using(db_alias).all().update(comment_count=0)
    Task.objects.using(db_alias).all().update(comment_count=0)

    event_counts = (
        Comment.objects.using(db_alias)
        .filter(parent_type="event", deleted_at__isnull=True)
        .values("parent_id")
        .annotate(total=Count("id"))
    )
    for row in event_counts:
        Event.objects.using(db_alias).filter(pk=row["parent_id"]).update(comment_count=row["total"])

    task_counts = (
        Comment.objects.using(db_alias)
        .filter(parent_type="task", deleted_at__isnull=True)
        .values("parent_id")
        .annotate(total=Count("id"))
    )
    for row in task_counts:
        Task.objects.using(db_alias).filter(pk=row["parent_id"]).update(comment_count=row["total"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0002_event_recurrence_end_date_task_recurrence_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='comment_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('done', 'Done')], default='pending', max_length=20),
        ),
        migrations.RunPython(backfill_calendar_comment_counts_and_statuses, noop_reverse),
    ]
