# Generated by Django 5.2.14 on 2026-05-17 14:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0003_event_comment_count_task_comment_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('event_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'calendar_general_event',
                'indexes': [models.Index(fields=['event_at'], name='calendar_ge_event_a_4081fe_idx')],
            },
        ),
    ]
