# Generated by Django 5.2.14 on 2026-05-18 02:22

from django.db import migrations, models


def migrate_access_types(apps, schema_editor):
    Event = apps.get_model("calendar", "Event")
    Task = apps.get_model("calendar", "Task")
    for Model in (Event, Task):
        Model.objects.filter(access_type__in=["group", "specific"]).update(access_type="mixed")


def reverse_migrate_access_types(apps, schema_editor):
    Event = apps.get_model("calendar", "Event")
    Task = apps.get_model("calendar", "Task")
    for Model in (Event, Task):
        Model.objects.filter(access_type="mixed").update(access_type="group")


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0004_add_general_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='access_close_group',
        ),
        migrations.RemoveField(
            model_name='task',
            name='access_close_group',
        ),
        migrations.AddField(
            model_name='event',
            name='access_close_group_ids',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='access_close_group_ids',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.RunPython(migrate_access_types, reverse_migrate_access_types),
        migrations.AlterField(
            model_name='event',
            name='access_type',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('all', 'All'), ('mixed', 'Mixed')], default='only_me', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='access_type',
            field=models.CharField(choices=[('only_me', 'Only Me'), ('all', 'All'), ('mixed', 'Mixed')], default='only_me', max_length=20),
        ),
    ]
