# Generated by Django 5.2.15 on 2026-07-14 12:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0029_subject_subjectgrade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('assigned_date', models.DateField()),
                ('due_date', models.DateField()),
                ('total_marks', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.academicyear')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.branch')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school.staff')),
            ],
            options={
                'db_table': 'assignments',
                'ordering': ['-assigned_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='homework.assignment')),
            ],
            options={
                'db_table': 'assignment_attachments',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_sections', to='homework.assignment')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.section')),
            ],
            options={
                'db_table': 'assignment_sections',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('marks', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('LATE', 'Late'), ('EVALUATED', 'Evaluated')], default='PENDING', max_length=20)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='school.student')),
            ],
            options={
                'db_table': 'assignment_submissions',
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmissionAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('assignment_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='homework.assignmentsubmission')),
            ],
            options={
                'db_table': 'assignment_submission_attachments',
            },
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('assigned_date', models.DateField()),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='school.academicyear')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='school.branch')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='school.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='school.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='school.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_homeworks', to='school.staff')),
            ],
            options={
                'db_table': 'homeworks',
                'ordering': ['-assigned_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeworkAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='homework.homework')),
            ],
            options={
                'db_table': 'homework_attachments',
            },
        ),
        migrations.CreateModel(
            name='HomeworkSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_sections', to='homework.homework')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.section')),
            ],
            options={
                'db_table': 'homework_sections',
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('teacher_remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUBMITTED', 'Submitted'), ('CHECKED', 'Checked')], default='PENDING', max_length=20)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='homework.homework')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_submissions', to='school.student')),
            ],
            options={
                'db_table': 'homework_submissions',
            },
        ),
        migrations.CreateModel(
            name='HomeworkSubmissionAttachment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_url', models.URLField()),
                ('homework_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='homework.homeworksubmission')),
            ],
            options={
                'db_table': 'homework_submission_attachments',
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['status'], name='assignments_status_7bfe3b_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['assigned_date'], name='assignments_assigne_972cde_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['due_date'], name='assignments_due_dat_708d3b_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['school', 'academic_year'], name='assignments_school__be25bf_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['grade', 'subject'], name='assignments_grade_i_c40e3a_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentattachment',
            index=models.Index(fields=['assignment'], name='assignment__assignm_61de3c_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsection',
            index=models.Index(fields=['assignment'], name='assignment__assignm_fb3a74_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsection',
            index=models.Index(fields=['section'], name='assignment__section_7b36bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsection',
            constraint=models.UniqueConstraint(fields=('assignment', 'section'), name='unique_assignment_section'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['status'], name='assignment__status_cd5870_idx'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmission',
            index=models.Index(fields=['assignment', 'student'], name='assignment__assignm_c9693f_idx'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='unique_assignment_submission'),
        ),
        migrations.AddIndex(
            model_name='assignmentsubmissionattachment',
            index=models.Index(fields=['assignment_submission'], name='assignment__assignm_644cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['status'], name='homeworks_status_039fc7_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['assigned_date'], name='homeworks_assigne_7f122c_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['due_date'], name='homeworks_due_dat_ffa0db_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['school', 'academic_year'], name='homeworks_school__807d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='homework',
            index=models.Index(fields=['grade', 'subject'], name='homeworks_grade_i_2acebd_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworksection',
            index=models.Index(fields=['homework'], name='homework_se_homewor_6960e8_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworksection',
            index=models.Index(fields=['section'], name='homework_se_section_604002_idx'),
        ),
        migrations.AddConstraint(
            model_name='homeworksection',
            constraint=models.UniqueConstraint(fields=('homework', 'section'), name='unique_homework_section'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['status'], name='homework_su_status_0c8085_idx'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmission',
            index=models.Index(fields=['homework', 'student'], name='homework_su_homewor_583d50_idx'),
        ),
        migrations.AddConstraint(
            model_name='homeworksubmission',
            constraint=models.UniqueConstraint(fields=('homework', 'student'), name='unique_homework_submission'),
        ),
        migrations.AddIndex(
            model_name='homeworksubmissionattachment',
            index=models.Index(fields=['homework_submission'], name='homework_su_homewor_8df403_idx'),
        ),
    ]
