# Generated by Django 5.2.15 on 2026-08-13 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
        ('school', '0032_alter_school_primary_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homeworksection',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework_sections', to='school.section'),
        ),
    ]
