# Generated by Django 5.2.15 on 2026-10-10 11:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0039_schooldocumenttype_unique_school_document_type_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_categories', to='school.school')),
            ],
            options={
                'db_table': 'gallery_categories',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('visibility', models.CharField(choices=[('SCHOOL', 'Entire School'), ('STAFF', 'Selected Staff'), ('GRADE', 'Selected Grades')], default='SCHOOL', max_length=20)),
                ('allow_downloads', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=False)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='school.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='school.school')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='galleries', to='gallery.gallerycategory')),
            ],
            options={
                'db_table': 'galleries',
                'ordering': ['-event_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryGrade',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visible_grades', to='gallery.gallery')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visible_galleries', to='school.grade')),
            ],
            options={
                'db_table': 'gallery_grades',
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='gallery.gallery')),
            ],
            options={
                'db_table': 'gallery_images',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryStaff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visible_staff', to='gallery.gallery')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visible_galleries', to='school.staff')),
            ],
            options={
                'db_table': 'gallery_staff',
            },
        ),
        migrations.AddConstraint(
            model_name='gallerycategory',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_gallery_category_per_school'),
        ),
        migrations.AddConstraint(
            model_name='gallerygrade',
            constraint=models.UniqueConstraint(fields=('gallery', 'grade'), name='unique_gallery_grade'),
        ),
        migrations.AddConstraint(
            model_name='gallerystaff',
            constraint=models.UniqueConstraint(fields=('gallery', 'staff'), name='unique_gallery_staff'),
        ),
    ]
