# Generated by Django 5.2.14 on 2026-05-23 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='feed_type',
        ),
    ]
