# Generated by Django 5.2.14 on 2026-05-24 16:55

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_feed_convention_alignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feed',
            index=models.Index(fields=['is_deleted', '-created_at'], name='feeds_active_created_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=django.contrib.postgres.indexes.GinIndex(fields=['access_family_ids'], name='feeds_access_family_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=django.contrib.postgres.indexes.GinIndex(fields=['access_close_group_ids'], name='feeds_access_cg_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='feed',
            index=django.contrib.postgres.indexes.GinIndex(fields=['access_user_ids'], name='feeds_access_user_gin_idx'),
        ),
        migrations.AddIndex(
            model_name='feedcomment',
            index=models.Index(fields=['feed', 'is_deleted', 'created_at'], name='feed_commen_feed_active_idx'),
        ),
        migrations.AddIndex(
            model_name='feedcomment',
            index=models.Index(fields=['feed', 'user', 'is_deleted'], name='feed_commen_feed_user_idx'),
        ),
        migrations.AddIndex(
            model_name='feedreaction',
            index=models.Index(fields=['feed'], name='feed_reactions_feed_idx'),
        ),
        migrations.AddIndex(
            model_name='feedshare',
            index=models.Index(fields=['user'], name='feed_shares_user_idx'),
        ),
    ]
