# Generated by Django 5.2.14 on 2026-05-24 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_feed_feeds_active_created_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='external_urls',
            field=models.JSONField(null=True),
        ),
    ]
