# Generated by Django 5.2.14 on 2026-05-24 17:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_feed_external_urls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSave',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='feed.feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_saves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_saves',
                'indexes': [models.Index(fields=['user', '-created_at'], name='feed_saves_user_created_idx'), models.Index(fields=['feed'], name='feed_saves_feed_idx')],
                'constraints': [models.UniqueConstraint(fields=('feed', 'user'), name='feed_saves_feed_user_unique')],
            },
        ),
    ]
