# Generated by Django 5.2.15 on 2026-07-09 09:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0028_remove_section_unique_section_per_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentTeacherMeeting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('meeting_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('meeting_mode', models.CharField(choices=[('OFFLINE', 'Offline'), ('ONLINE', 'Online')], default='OFFLINE', max_length=20)),
                ('meeting_type', models.CharField(choices=[('GENERAL', 'General'), ('ACADEMIC', 'Academic'), ('RESULT_DISCUSSION', 'Result Discussion'), ('PROGRESS_REVIEW', 'Progress Review'), ('BEHAVIORAL', 'Behavioral'), ('ORIENTATION', 'Orientation'), ('OTHER', 'Other')], default='GENERAL', max_length=30)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_teacher_meetings', to='school.academicyear')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_teacher_meetings', to='school.branch')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_teacher_meetings', to='school.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_teacher_meetings', to='school.school')),
            ],
            options={
                'db_table': 'parent_teacher_meetings',
                'ordering': ['-meeting_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='ParentTeacherMeetingResponse',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('response_status', models.CharField(choices=[('PENDING', 'Pending'), ('ATTENDING', 'Attending'), ('NOT_ATTENDING', 'Not Attending')], default='PENDING', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('attendance_status', models.CharField(choices=[('NOT_MARKED', 'Not Marked'), ('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='NOT_MARKED', max_length=20)),
                ('attended_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_responses', to='ptm.parentteachermeeting')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_teacher_meeting_responses', to='school.student')),
            ],
            options={
                'db_table': 'parent_teacher_meeting_responses',
            },
        ),
        migrations.CreateModel(
            name='ParentTeacherMeetingSection',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_sections', to='ptm.parentteachermeeting')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_teacher_meetings', to='school.section')),
            ],
            options={
                'db_table': 'parent_teacher_meeting_sections',
            },
        ),
        migrations.AddIndex(
            model_name='parentteachermeeting',
            index=models.Index(fields=['school', 'meeting_date'], name='ptm_school_date_idx'),
        ),
        migrations.AddIndex(
            model_name='parentteachermeeting',
            index=models.Index(fields=['school', 'branch', 'status'], name='ptm_branch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='parentteachermeeting',
            index=models.Index(fields=['grade', 'meeting_date'], name='ptm_grade_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='parentteachermeetingresponse',
            constraint=models.UniqueConstraint(fields=('meeting', 'student'), name='unique_student_response_per_ptm'),
        ),
        migrations.AddConstraint(
            model_name='parentteachermeetingsection',
            constraint=models.UniqueConstraint(fields=('meeting', 'section'), name='unique_section_per_ptm'),
        ),
    ]
