# Generated by Django 5.2.15 on 2026-07-14 04:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptm', '0001_initial'),
        ('school', '0028_remove_section_unique_section_per_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentTeacherMeetingStaff',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('created_by', models.CharField(editable=False, max_length=255, null=True)),
                ('updated_by', models.CharField(max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=255, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('responsibility', models.CharField(choices=[('HOST', 'Host'), ('PARTICIPANT', 'Participant'), ('OBSERVER', 'Observer')], default='PARTICIPANT', max_length=20)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_staffs', to='ptm.parentteachermeeting')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ptm_meetings', to='school.staff')),
            ],
            options={
                'db_table': 'parent_teacher_meeting_staffs',
                'constraints': [models.UniqueConstraint(fields=('meeting', 'staff'), name='unique_staff_per_ptm')],
            },
        ),
    ]
